### ISSUE TITLE
Clarify what "Send Sales Data to MailChimp" means in the metabox.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-mail-chimp#26]
The metabox for sending ecommerce sales data to mailchimp seems to lead customers to believe that clicking "Send Data" will import their customers' email addresses into their MailChimp email lists. We have added a note about this to our docs but still get tickets about it (and I forgot myself).

We should add a descriptive note to the metabox to explain what this means and what it is actually doing so the customer understands. We should also add additional detail to a tool tip.

**Comment by davekiss** [comment]
This functionality is going to be removed in the API 3 rewrite. All store data will be synced with a MailChimp list, though, the customer won't automatically be subscribed to the list if they are not present on the list.

Customers will instead be added as a **transactional** subscriber, which allows them to be included in MailChimp reports and segments, but they won't receive outgoing newsletters until they explicitly opt in.

**Comment by brianhogg** [comment]
Any rational behind the major functionality change?

Since they're a customer that's implicit consent to be added to a list in every spam legislation I've seen, and many like myself are mostly using that list for a small amount of follow up automation and any security or major update emails.  Seems it should be an option to auto subscribe as now.

Would they still be added to the main list selected under the Settings at least?

**Comment by davekiss** [comment]
@brianhogg sorry, my comment was not clear enough.

What I mean is that any backfilled customer data might make most sense to tag as transactional rather than a subscriber if they aren't already on the list from a previous subscription. In my mind, consent to opt in to a list (or auto-subscribe, based on the store owner's preference) may not necessarily apply retroactively, but to customers moving forward.

This isn't so much a technical barrier rather than an ethical decision.  I'm happy to hear your opinions and will go with whatever is the popular consensus @pippinsplugins @cklosowski

**Comment by brianhogg** [comment]
Thanks for clarifying!

I think the same thing should happen on purchase as it does on backfill.  This way if there's ever an issue with the plugin or communication with MailChimp, the backfill can get everything (subscriptions and ecomm data) back in sync again.

I could definitely see it being an option to subscribe or not subscribe, but stay the same as current for those upgrading the plugun.

**Comment by davekiss** [comment]
@pippinsplugins @cklosowski can you guys weigh in here so the behavior is as expected when `api3` gets merged?

**Comment by pippinsplugins** [comment]
I do not feel we should allow store admins to backfill customer subscriptions. Transactional data, sure, but not actual list subscriptions. That'd be too easy to abuse.

If someone wants to do that, they can export the customer list and import it through MailChimp's interface. That way at least they are shown all of the prompts by MailChimp that alert them to the potential abuse.

**Comment by davekiss** [comment]
@pippinsplugins Cool, I'll leave this as `false` then, and leave it up to a developer if they wish to override manually with a filter.

For details on what this flag does, see http://developer.mailchimp.com/documentation/mailchimp/guides/getting-started-with-ecommerce/#about-subscribers-and-customers
