### ISSUE TITLE
Improve experience for refreshing mailing lists

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-mail-chimp#9]
We've been asked about this quite a bit and people sometimes think the extension is broken because their new lists don't show up in their dashboard. We tell them to save settings, but they don't know that unless we tell them.

A customer suggested we add a button/link to refresh the lists. At the very least, having the description under the list dropdown tell them to save settings to refresh would be great.

**Comment by pippinsplugins** [comment]
:+1: I'd be fine with a refresh button.

**Comment by davekiss** [comment]
This user experience has been vastly improved in the `api3` branch, which introduces the concept of "Connected Lists"

https://github.com/easydigitaldownloads/edd-mail-chimp/commit/d969ef82c2584b9f71dd24d3cc72831657a0f34e#diff-0a0509cb4a27ce341cf836f95f788497

Instead of fetching and caching all of a users lists in several different places throughout the plugin, we'll always fetch the latest remote data on the settings page and allow a user to connect MailChimp lists of their choice to EDD. Once connected, the user can then specify which lists that customers should be subscribed to, where ecommerce data should be synced, etc.
